/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NY7sYQ6EuKV
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function Card2() {
  return (
    <div className="container mx-auto px-4 py-12 md:px-6 lg:py-16 text-white">
      <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
        
        <div className="space-y-4 text-white">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl ">
            STATISTICS AND BENEFITS
          </h2>
          <p className="">
            <ul>
              <li>
                Efficiency; deep 6ai can enroll pateints within minutes compared
                to traditional methods which three times faster and finds over
                25 percent of new patients. So, the users of this tool need to
                spend only half of the time compared to other methods. Deep6 ai
                enabled several healthcare organisations such as Texas medical
                centre and cidar-sinai medical centre for patient enrollment.
              </li>
              <li>
                ACCURACY ; through the analysing of electronic medical reports
                this ai found 15 -20 percent of patients , those are precise
                match for the studies that might be missed during manual
                selection. These benefits highlights that deep 6 ai will reduce
                the time, cost, labour and effort of researchers or sponsers by
                giving precise data.
              </li>
            </ul>
          </p>
        </div>
        <div className="space-y-4">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
            TEXAS MEDICAL SUCCESS
          </h2>
          <p className="">
            For the purpose of a clinical trial they were needed a dozen of
            matching participants and it took about six months to hit the target
            by selecting manually. In contrast deep 6 ai was enrolled 80
            participants within minutes. So that, they rolled out over 60
            medical institutions to switch the process of recruitment.
          </p>
        </div>
      </div>
    </div>
  );
}
