/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/eyx4CYHxECc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Caudex } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CollapsibleTrigger, CollapsibleContent, Collapsible } from "@/components/ui/collapsible"
import { JSX, SVGProps } from "react"
import image from "../../public/hero.svg"
import { Card } from "./card"
import { Card2 } from "./card2"
import { Manu } from "./manu"
import { Ref } from "./ref"
import { Refic } from "./refic"
export function Hero() {
  return (
    <div className="relative w-full min-h-[200vh] bg-[url(/hero.svg)] bg-cover bg-center bg-no-repeat bg-[#f5f5f5] dark:bg-gray-950">
      <div className="absolute inset-0 bg-gray-950/80 dark:bg-gray-950/90" />
      <div className="relative z-10 container mx-auto px-4 md:px-6 py-24 md:py-32 lg:py-20 flex flex-col items-center justify-center text-center space-y-6">
        <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-white tracking-tighter">Deep 6 AI</h1>
       <p className="max-w-[700px] text-lg md:text-xl text-gray-200 text-justify">
  Clinical trials play a crucial role in patient care. These trials are really time-consuming and complex processes, but due to the advancement of technology, everything has become more efficient and faster than in the past. The implementation of AI in healthcare helps researchers in all aspects.
</p>

<Collapsible className="w-full max-w-md">
  <CollapsibleTrigger className="flex items-center justify-between w-full bg-white dark:bg-gray-900 rounded-md px-4 py-3 text-gray-900 dark:text-gray-50 font-medium hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus-visible:ring focus-visible:ring-gray-400 dark:focus-visible:ring-gray-600">
    What is it?
    <ChevronDownIcon className="h-5 w-5 text-gray-500 dark:text-gray-400 transition-transform [&[data-state=open]]:rotate-180" />
  </CollapsibleTrigger>
  <CollapsibleContent className="bg-white dark:bg-gray-900 rounded-md px-4 py-3 text-gray-700 dark:text-gray-400 text-justify">
    Recruitment of participants is an important and most hardest part of a research. Deep 6 AI helps researchers, healthcare organizations, and patients by accelerating the process of patient recruitment by providing appropriate participants by analyzing large amounts of real-time data. This uses artificial intelligence (AI) and natural language processing (NLP) to enroll participants.
  </CollapsibleContent>
</Collapsible>
<Collapsible className="w-full max-w-md">
  <CollapsibleTrigger className="flex items-center justify-between w-full bg-white dark:bg-gray-900 rounded-md px-4 py-3 text-gray-900 dark:text-gray-50 font-medium hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus-visible:ring focus-visible:ring-gray-400 dark:focus-visible:ring-gray-600">
    How is it used?
    <ChevronDownIcon className="h-5 w-5 text-gray-500 dark:text-gray-400 transition-transform [&[data-state=open]]:rotate-180" />
  </CollapsibleTrigger>
  <CollapsibleContent className="bg-white dark:bg-gray-900 rounded-md px-4 py-3 text-gray-700 dark:text-gray-400 text-justify">
    PATIENT RECRUITMENT:
    <ul>
      <li>Provides patient recruitment tool to select precise trial participants by analyzing structured data (like ICD-10 codes) and unstructured data (such as medical reports). Then, it represents the information as dynamic graphs which provide a clear view of suitable participants for the inclusion criteria.</li>
      <li>Selection process will be completed within a few minutes rather than long waits.</li>
    </ul>
    TRIAL DESIGN AND SITE SELECTION:
    <ul>
      <li>Clinical trials are designed by analyzing a huge amount of real-world data so that the efficiency and accuracy will be high.</li>
      <li>The sites for the studies are selected by identifying the availability of patients with the assurance of a high success rate.</li>
    </ul>
    DATA COLLECTION AND ANALYSES:
    <ul>
      <li>Data are collected and analyzed from different sources within a short period and combined to identify eligible human subjects.</li>
    </ul>
  </CollapsibleContent>
</Collapsible>
<Collapsible className="w-full max-w-md">
  <CollapsibleTrigger className="flex items-center justify-between w-full bg-white dark:bg-gray-900 rounded-md px-4 py-3 text-gray-900 dark:text-gray-50 font-medium hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus-visible:ring focus-visible:ring-gray-400 dark:focus-visible:ring-gray-600">
    Has it already been used in clinical trials?
    <ChevronDownIcon className="h-5 w-5 text-gray-500 dark:text-gray-400 transition-transform [&[data-state=open]]:rotate-180" />
  </CollapsibleTrigger>
  <CollapsibleContent className="bg-white dark:bg-gray-900 rounded-md px-4 py-3 text-gray-700 dark:text-gray-400 text-justify">
    Deep 6 AI tool has been used in several clinical trials to accelerate the time period. For example, Deep 6 AI was used in a study sponsored by the National Cancer Institute to find whether there is a link between high blood sugar and pancreatic cancer. In this study, the research team found only 1 participant over five weeks, but Deep 6 AI found 6 participants who were exactly eligible for the study within minutes. This implies the efficiency of this tool.
  </CollapsibleContent>
</Collapsible>
      <Manu/>
      <Card/>
      <Card2/>
      </div>
    </div>
  )
}

function ChevronDownIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}