/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FUphwuEDvjW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardDescription, CardHeader, CardContent, Card } from "@/components/ui/card"
import { JSX, SVGProps } from "react"


export function Manu() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Deep 6 AI</CardTitle>
        <CardDescription>Pasadena, California</CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="flex items-center gap-4">
          <GlobeIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
          <a className="text-blue-600 hover:underline" href="#" rel="noopener noreferrer" target="_blank">
            www.deep6.ai
          </a>
        </div>
        <div className="flex items-center gap-4">
          <MailIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
          <a className="text-blue-600 hover:underline" href="#">
            nour@deep6.ai
          </a>
        </div>
        <div className="flex items-center gap-4">
          <UserIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
          <div>
            <div className="font-medium">Nour Malki</div>
            <div className="text-gray-500 dark:text-gray-400">Communications and Content Specialist</div>
          </div>
        </div>
        <div className="flex items-center gap-4 pl-12">
          <div>
            <div className="font-medium">OTHER VALUABLE PRODUCTS;</div>
            <div className="text-gray-500 dark:text-gray-400">Cohort builder and patient recommendor</div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

function GlobeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  )
}


function MailIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
