/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/riUbc4o9jua
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Ref() {
  return (
<div className="bg-white dark:bg-gray-950 rounded-lg shadow-lg overflow-hidden">
  <div className="p-2">
    <h2 className="text-2xl font-bold mb-4">REFERENCE</h2>
    <p className="text-gray-500 dark:text-gray-400">
    Salian, I. (2020, March 4). Deep 6 Uses AI to Recruit Patients to Clinical Trials | NVIDIA Blog. NVIDIA Blog. https://blogs.nvidia.com/blog/deep-6-ai-clinical-trials/
Rani, A. (2024, January 8). Deep 6 AI and Graticule develop clinical trial recruitment algorithm. Clinical Trials Arena. https://www.clinicaltrialsarena.com/news/deep-6-ai-graticule-algorithm/
Deep 6 AI uses AWS to accelerate clinical trial recruitment and digitize clinical workflows (12:20). (n.d.). [Video]. Amazon Web Services, Inc. https://aws.amazon.com/solutions/case-studies/deep-6-ai/
Carle Foundation Hospital. (n.d.). Carle taps into artificial intelligence to advance clinical trials | Carle.org. https://carle.org/newsroom/community/2022/02/carle-taps-into-artificial-intelligence-to-advance
</p>
  </div>
</div>


  )
}
