/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Dma33ZtyfxN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function Refic() {
  return (
    <div className="space-y-4">
      <h2 className="text-lg font-semibold">REFERENCE</h2>
      <div className="space-y-2">
        <p>
          Salian, I. (2020, March 4). <em>Deep 6 Uses AI to Recruit Patients to Clinical Trials | NVIDIA Blog</em>.
          NVIDIA Blog.{""}
          <a className="text-blue-600" href="#">
            https://blogs.nvidia.com/blog/deep-6-ai-clinical-trials/
          </a>
        </p>
        <p>
          Rani, A. (2024, January 8). <em>Deep 6 AI and Graticule develop clinical trial recruitment algorithm</em>.
          Clinical Trials Arena.{""}
          <a className="text-blue-600" href="#">
            https://www.clinicaltrialsarena.com/news/deep-6-ai-graticule-algorithm/
          </a>
        </p>
        <p>
          <em>Deep 6 AI uses AWS to accelerate clinical trial recruitment and digitize clinical workflows</em> (12:20).
          (n.d.). [Video]. Amazon Web Services, Inc.{""}
          <a className="text-blue-600" href="#">
            https://aws.amazon.com/solutions/case-studies/deep-6-ai/
          </a>
        </p>
        <p>
          Carle Foundation Hospital. (n.d.). <em>Carle taps into artificial intelligence to advance clinical trials</em>
          . Carle.org.{""}
          <a className="text-blue-600" href="#">
            https://carle.org/newsroom/community/2022/02/carle-taps-into-artificial-intelligence-to-advance
          </a>
        </p>
      </div>
    </div>
  )
}
